require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

source 'https://github.com/react-native-tvos/react-native-tvos-podspecs.git'
source 'https://cdn.cocoapods.org/'
install! 'cocoapods', :deterministic_uuids => false

target 'MediasetInfinityNew' do

  platform :ios, '12.4'

  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'MediasetInfinityNewTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'MediasetInfinityNew-tvOS' do

  platform :tvos, '12.4'

  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes not yet available on tvOS
    :hermes_enabled => false,
    :fabric_enabled => flags[:fabric_enabled],
    # An abosolute path to your application root.
    :app_path => "#{Dir.pwd}/.."
  )

  target 'MediasetInfinityNew-tvOSTests' do
    inherit! :complete
    # Pods for testing
  end
end

post_install do |installer|
  react_native_post_install(installer)
  __apply_Xcode_12_5_M1_post_install_workaround(installer)
     installer.pods_project.targets.each do |target|
       if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
         target.build_configurations.each do |config|
             config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
         end
       end
  end
end
