import {
  CarouselTemplate,
  Size,
  LocalCarouselTemplate,
  Rect,
  LayoutTemplate,
  CarouselLayout
} from '../models/app.models';


export const LayoutTemplates:LayoutTemplate<CarouselLayout> = {
  [LocalCarouselTemplate.BillboardBigCollection]: {
    width: 0,
    height: -240,
    itemLayout: {
      x: 20,
      y: 0,
      width: 160,
      height: 80,
      showTitle: false,
    },
  },
  [LocalCarouselTemplate.BillboardCollection]:{
    width: 0,
    height: -120,
    itemLayout: {
      x: 40,
      y: 0,
      width: 260,
      height: 195,
      showTitle: false,
    },
  },
  [LocalCarouselTemplate.BillboardCollectionInline]:{
    width: 0,
      height: -340,
      itemLayout: {
        x: 20,
        y: 0,
        width: 320,
        height: 180,
        showTitle: false,
      },
  },
  [LocalCarouselTemplate.VideoBrandedCollection]:{
      width: 0,
      height: 440,
      itemLayout: {
        x: 40,
        y: 0,
        width: 320,
        height: 280,
        showTitle: true,
    },
  },
  [LocalCarouselTemplate.OptionCollection]:{
    width: 0,
    height: 420,
    itemLayout: {
      x: 40,
      y: 0,
      width: 315,
      height: 240,
      showTitle: false,
    },
  },
  [LocalCarouselTemplate.OnAirCollection]:{
    width: 0,
    height: 440,
    itemLayout: {
      x: 40,
      y: 0,
      width: 320,
      height: 280,
      showTitle: true,
    },
  },
  [LocalCarouselTemplate.ScheduleCollection]:{
    width: 0,
    height: 440,
    itemLayout: {
      x: 40,
      y: 0,
      width: 320,
      height: 280,
      showTitle: true,
    },
  },
  [LocalCarouselTemplate.CtvLanding]:{
    width: 0,
    height: 320,
    itemLayout: {
      x: 20,
      y: 0,
      width: 320,
      height: 280,
      showTitle: true,
    },
  },
  [LocalCarouselTemplate.NavCollection]:{
    width: 0,
    height: 320,
    itemLayout: {
      x: 20,
      y: 0,
      width: 240,
      height: 120,
      showTitle: false,
    },
  },
  [LocalCarouselTemplate.KeyFrameCollection]:{
    width: 0,
    height: 440,
    itemLayout: {
      x: 40,
      y: 0,
      width: 320,
      height: 280,
      showTitle: true,
    },
  },
  [LocalCarouselTemplate.PosterCollection]:{
    width: 0,
    height: 480,
    itemLayout: {
      x: 30,
      y: 0,
      width: 180,
      height: 320,
      showTitle: false,
    },
  },
  [LocalCarouselTemplate.GridKeyFrameCollection]:{
    width: 0,
    height: 240,
    itemLayout: {
      x: 20,
      y: 0,
      width: 180,
      height: 102,
      showTitle: true,
    },
  },
  [LocalCarouselTemplate.GridPosterCollection]:{
    width: 0,
    height: 400,
    itemLayout: {
      x: 20,
      y: 0,
      width: 180,
      height: 160,
      showTitle: true,
    },
  }
};


export const CarouselTemplates: Array<CarouselTemplate> = [
  {
    collection: ['HeroCollection'],
    template: ['BILLBOARD'],
    layout: ['BIG'],
    localTemplate: LocalCarouselTemplate.BillboardBigCollection,
    templateImage: 'editorial_image_hero',
    fallbackTemplateImage: 'image_header_poster',
    itemsTemplateImage: 'editorial_image_hero',
    itemsFallbackTemplateImage: 'image_header_poster',
    itemsLen: 1,
    itemsHorizontalSpace: 0,
    itemsShowTitle: true,
    isGrid: false,
    carouselLayout: {
      width: 0,
      height: -160,
      itemLayout: {
        x: 20,
        y: 0,
        width: 160,
        height: 80,
        showTitle: false,
      },
    },
  },
  {
    collection: ['HeroCollection'],
    template: ['BILLBOARD'],
    layout: [],
    localTemplate: LocalCarouselTemplate.BillboardCollection,
    templateImage: 'editorial_image_hero',
    fallbackTemplateImage: 'image_header_poster',
    itemsTemplateImage: 'editorial_image_hero',
    itemsFallbackTemplateImage: 'image_header_poster',
    itemsLen: 5,
    itemsHorizontalSpace: 30,
    itemsShowTitle: false,
    isGrid: false,
    carouselLayout: {
      width: 0,
      height: -160,
      itemLayout: {
        x: 20,
        y: 0,
        width: 160,
        height: 80,
        showTitle: false,
      },
    },
  },
  {
    collection: ['HeroCollection'],
    template: ['INLINE'],
    layout: ['SLIDER'],
    localTemplate: LocalCarouselTemplate.BillboardCollectionInline,
    templateImage: 'editorial_image_hero',
    fallbackTemplateImage: 'editorial_image_banner',
    itemsTemplateImage: 'editorial_image_hero',
    itemsFallbackTemplateImage: 'editorial_image_banner',
    itemsLen: 5,
    itemsHorizontalSpace: 80,
    itemsShowTitle: false,
    isGrid: false,
    carouselLayout: {
      width: 0,
      height: -160,
      itemLayout: {
        x: 10,
        y: 0,
        width: 160,
        height: 40,
        showTitle: false,
      },
    },
  },
  {
    collection: ['VideoCollection'],
    template: ['VIDEO_BRANDED'],
    layout: ['SLIDER'],
    localTemplate: LocalCarouselTemplate.VideoBrandedCollection,
    templateImage: 'image_keyframe_poster',
    fallbackTemplateImage: 'image_header_poster',
    itemsTemplateImage: 'image_keyframe_poster',
    itemsFallbackTemplateImage: 'image_header_poster',
    itemsLen: 4,
    itemsHorizontalSpace: 30,
    itemsShowTitle: true,
    isGrid: false,
    carouselLayout: {
      width: 0,
      height: 240,
      itemLayout: {
        x: 20,
        y: 0,
        width: 180,
        height: 180,
        showTitle: true,
      },
    },
  },
  {
    collection: [
      'OptionCollection',
      'PlaceholderCollection',
      'UserlistCollection',
    ],
    template: ['OPTIONS'],
    layout: ['SLIDER'],
    localTemplate: LocalCarouselTemplate.OptionCollection,
    templateImage: '',
    fallbackTemplateImage: '',
    itemsTemplateImage: 'editorial_image_keyframe',
    itemsFallbackTemplateImage: '',
    itemsLen: 904,
    itemsHorizontalSpace: 30,
    itemsShowTitle: false,
    isGrid: false,
  },
  {
    collection: ['OnAirCollection'],
    template: [],
    layout: [],
    localTemplate: LocalCarouselTemplate.OnAirCollection,
    templateImage: '',
    fallbackTemplateImage: '',
    itemsTemplateImage: 'editorial_image_channel_logo',
    itemsFallbackTemplateImage: '',
    itemsLen: 2,
    itemsHorizontalSpace: 30,
    itemsShowTitle: true,
    isGrid: false,
  },
  {
    collection: ['ScheduleCollection'],
    template: [],
    layout: [],
    localTemplate: LocalCarouselTemplate.ScheduleCollection,
    templateImage: 'editorial_image_keyframe',
    fallbackTemplateImage: 'editorial_image_content_preview',
    itemsTemplateImage: 'editorial_image_keyframe',
    itemsFallbackTemplateImage: 'editorial_image_content_preview',
    itemsLen: 2,
    itemsHorizontalSpace: 40,
    itemsShowTitle: true,
    isGrid: false,
    carouselLayout: {
      width: 0,
      height: 240,
      itemLayout: {
        x: 20,
        y: 0,
        width: 180,
        height: 180,
        showTitle: true,
      },
    },
  },
  {
    collection: ['GenericCollection'],
    template: ['CTV_LANDING'],
    layout: ['SLIDER'],
    localTemplate: LocalCarouselTemplate.CtvLanding,
    templateImage: '',
    fallbackTemplateImage: '',
    itemsTemplateImage: '',
    itemsFallbackTemplateImage: '',
    itemsLen: 1,
    itemsHorizontalSpace: 30,
    itemsShowTitle: true,
    isGrid: false,
  },
  {
    collection: ['NavCollection'],
    template: ['NAV'],
    layout: ['SLIDER'],
    localTemplate: LocalCarouselTemplate.NavCollection,
    templateImage: '',
    fallbackTemplateImage: '',
    itemsTemplateImage: '',
    itemsFallbackTemplateImage: '',
    itemsLen: 4,
    itemsHorizontalSpace: 30,
    itemsShowTitle: true,
    isGrid: false,
  },
  {
    collection: [
      'MixedCollection',
      'SeasonCollection',
      'SeriesCollection',
      'PlaceholderCollection',
      'UserlistCollection',
      'MovieCollection',
    ],
    template: ['POSTER'],
    layout: ['SLIDER'],
    localTemplate: LocalCarouselTemplate.PosterCollection,
    templateImage: 'image_vertical',
    fallbackTemplateImage: 'image_header_poster',
    itemsTemplateImage: 'image_vertical',
    itemsFallbackTemplateImage: 'image_header_poster',
    itemsLen: 4,
    itemsHorizontalSpace: 30,
    itemsShowTitle: true,
    isGrid: false,
    carouselLayout: {
      width: 0,
      height: 280,
      itemLayout: {
        x: 10,
        y: 0,
        width: 102,
        height: 260,
        showTitle: false,
      },
    },
  },
  {
    collection: [
      'VideoCollection',
      'MixedCollection',
      'PlaceholderCollection',
      'UserlistCollection',
    ],
    template: ['KEYFRAME', 'PLAYLIST','VIDEO_BRANDED_CAROUSEL'],
    layout: ['SLIDER'],
    localTemplate: LocalCarouselTemplate.KeyFrameCollection,
    templateImage: 'image_keyframe_poster',
    fallbackTemplateImage: 'image_header_poster',
    itemsTemplateImage: 'image_keyframe_poster',
    itemsFallbackTemplateImage: 'image_header_poster',
    itemsLen: 4,
    itemsHorizontalSpace: 30,
    itemsShowTitle: true,
    isGrid: false,
  },
  {
    collection: [
      'VideoCollection',
      'MovieCollection',
      'MixedCollection',
      'SeasonCollection',
      'SeriesCollection',
      'PlaceholderCollection',
      'UserlistCollection',
    ],
    template: ['KEYFRAME', 'PLAYLIST'],
    layout: ['GRID'],
    localTemplate: LocalCarouselTemplate.GridKeyFrameCollection,
    templateImage: '',
    fallbackTemplateImage: '',
    itemsTemplateImage: 'image_keyframe_poster',
    itemsFallbackTemplateImage: 'image_horizontal_cover',
    itemsLen: 4,
    itemsHorizontalSpace: 30,
    itemsShowTitle: true,
    isGrid: true,
  },
  {
    collection: [
      'VideoCollection',
      'MovieCollection',
      'MixedCollection',
      'SeasonCollection',
      'SeriesCollection',
      'PlaceholderCollection',
      'UserlistCollection',
    ],
    template: ['POSTER'],
    layout: ['GRID'],
    localTemplate: LocalCarouselTemplate.GridPosterCollection,
    templateImage: '',
    fallbackTemplateImage: '',
    itemsTemplateImage: 'image_vertical',
    itemsFallbackTemplateImage: '',
    itemsLen: 7,
    itemsHorizontalSpace: 30,
    itemsShowTitle: true,
    isGrid: true,
  },
];

export const HorinzotalGridItems: Record<number, Rect> = {
  2: {x: 40, y: 0, width: 840, height: 230},
  3: {x: 40, y: 0, width: 560, height: 315},
  4: {x: 30, y: 0, width: 400, height: 230},
  5: {x: 40, y: 0, width: 320, height: 180},
  6: {x: 40, y: 0, width: 260, height: 195},
  7: {x: 8, y: 0, width: 260, height: 195},
  904: {x: 40, y: 0, width: 341, height: 260},
};

export const VerticalGridItems: Record<number, Rect> = {
  2: {x: 30, y: 0, width: 200, height: 300},
  3: {x: 30, y: 0, width: 200, height: 300},
  4: {x: 30, y: 0, width: 220, height: 330},
  5: {x: 30, y: 0, width: 220, height: 330},
  6: {x: 30, y: 0, width: 220, height: 330},
  7: {x: 30, y: 0, width: 220, height: 330},
};

export const ImageSizeFromTemplate: Record<string, Array<Size>> = {
  editorial_image_banner: [
    {width: 320, height: 260},
    {width: 768, height: 384},
    {width: 960, height: 289},
    {width: 1024, height: 347},
    {width: 1440, height: 433},
    {width: 1920, height: 578},
  ],
  editorial_image_brand_content_preview: [
    {width: 320, height: 280},
    {width: 768, height: 480},
    {width: 900, height: 394},
    {width: 1360, height: 595},
    {width: 1440, height: 630},
  ],
  editorial_image_hero: [
    {width: 320, height: 280},
    {width: 768, height: 480},
    {width: 900, height: 394},
    {width: 1360, height: 595},
    {width: 1440, height: 630},
  ],
  image_header_poster: [
    {width: 320, height: 260},
    {width: 320, height: 280},
    {width: 768, height: 384},
    {width: 768, height: 480},
    {width: 900, height: 394},
    {width: 960, height: 289},
    {width: 1440, height: 433},
    {width: 1440, height: 630},
  ],
  editorial_image_keyframe: [
    {width: 240, height: 135},
    {width: 265, height: 148},
    {width: 292, height: 165},
    {width: 360, height: 203},
    {width: 391, height: 220},
    {width: 652, height: 367},
    {width: 1200, height: 630},
    {width: 1280, height: 720},
  ],
  image_keyframe_poster: [
    {width: 240, height: 135},
    {width: 265, height: 148},
    {width: 292, height: 165},
    {width: 360, height: 203},
    {width: 391, height: 220},
    {width: 652, height: 367},
    {width: 1200, height: 630},
    {width: 1280, height: 720},
  ],
  image_horizontal_cover: [{width: 704, height: 396}],
  logo_horizontal: [{width: 320, height: 128}],
  brand_logo: [
    {width: 72, height: 72},
    {width: 120, height: 120},
    {width: 210, height: 210},
  ],
  image_vertical: [
    {width: 140, height: 210},
    {width: 168, height: 252},
    {width: 264, height: 396},
  ],
};
